### ISSUE TITLE
Switch to Jetpack Compose

### ISSUE THREAD

**Issue by jao-johnreginald** [jao-johnreginald/hello-world#7]
Should we switch from xml to jetpack compose? I mean modern apps are doing it right now but we need to refactor the whole project!

**Comment by Jao-Steven-Rey-C** [comment]
Switching to Jetpack Compose is too much of a task. We need to launch our app to Google Play Store first before refactoring our code.

**Comment by jao-johnreginald** [comment]
Sounds good, let's stick with xml for now.
